name: Deploy to ECR and EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Login to AWS ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
        region: ${{ secrets.AWS_REGION }}

    # Build Docker image and push to ECR
    - name: Build and push Docker image to ECR
      run: |
        docker build -t ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }} .
        docker push ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}

    # Deploy image from ECR to EKS
    #- name: Update Kubernetes Deployment
      #run: |
        #kubectl set image deployment/<deployment_name> <container_name>=${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}
